/*
-- Query: SELECT * FROM movies.movies
LIMIT 0, 1000

-- Date: 2019-12-24 15:29
*/

USE `movies`;

INSERT INTO `movies` (`movieId`,`title`,`director`,`description`,`released`) VALUES (5,'The Godfather','Francis Ford Coppola','The Godfather \"Don\" Vito Corleone is the head of the Corleone mafia family in New York. He is at the event of his daughter\'s wedding. Michael, Vito\'s youngest son and a decorated WW II Marine is also present at the wedding. Michael seems to be uninterested in being a part of the family business. Vito is a powerful man, and is kind to all those who give him respect but is ruthless against those who',1972);
INSERT INTO `movies` (`movieId`,`title`,`director`,`description`,`released`) VALUES (6,'The Godfather: Part II','Francis Ford Coppola','The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.',1974);
INSERT INTO `movies` (`movieId`,`title`,`director`,`description`,`released`) VALUES (7,'The Dark Knight','Christopher Nolan','When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',2008);
INSERT INTO `movies` (`movieId`,`title`,`director`,`description`,`released`) VALUES (8,'The Shawshank Redemption','Frank Darabont','Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the man\'s unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red.',1994);
INSERT INTO `movies` (`movieId`,`title`,`director`,`description`,`released`) VALUES (9,'12 Angry Men','   Sidney Lumet','The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young man is guilty or innocent of murdering his father. What begins as an open-and-shut case of murder soon becomes a detective story that presents a succession of clues creating doubt, and a mini-drama of each of the jurors\' prejudices and preconceptions about the trial, the accused, and each oth',1957);
INSERT INTO `movies` (`movieId`,`title`,`director`,`description`,`released`) VALUES (10,'Schindler\'s List',' Steven Spielberg','In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',1993);
INSERT INTO `movies` (`movieId`,`title`,`director`,`description`,`released`) VALUES (11,'The Lord of the Rings: The Return of the King',' Peter Jackson','Gandalf and Aragorn lead the World of Men against Sauron\'s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.',2003);
INSERT INTO `movies` (`movieId`,`title`,`director`,`description`,`released`) VALUES (12,'Pulp Fiction',' Quentin Tarantino','The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',1994);
INSERT INTO `movies` (`movieId`,`title`,`director`,`description`,`released`) VALUES (13,'The Good, the Bad and the Ugly','Sergio Leone','A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.',1966);
INSERT INTO `movies` (`movieId`,`title`,`director`,`description`,`released`) VALUES (14,'Fight Club','David Fincher','An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.',1999);
INSERT INTO `movies` (`movieId`,`title`,`director`,`description`,`released`) VALUES (15,'The Lord of the Rings: The Fellowship of the Ring','Peter Jackson','An ancient Ring thought lost for centuries has been found, and through a strange twist of fate has been given to a small Hobbit named Frodo. When Gandalf discovers the Ring is in fact the One Ring of the Dark Lord Sauron, Frodo must make an epic quest to the Cracks of Doom in order to destroy it. However, he does not go alone. He is joined by Gandalf, Legolas the elf, Gimli the Dwarf, Aragorn, Bor',2001);
INSERT INTO `movies` (`movieId`,`title`,`director`,`description`,`released`) VALUES (16,'Forrest Gump',' Robert Zemeckis','The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other history unfold through the perspective of an Alabama man with an IQ of 75.',1994);
